### ISSUE TITLE
LogIn parameter error 

### ISSUE THREAD

**Issue by stevenh-ACM** [Acumatica/AcumaticaRESTAPIClientForCSharp#19]
Calling LogIn with username, password works. 

However if you pass in all 5 specified (intellisense) an error returns stating that the company and tenant parameters can not be specified at the same time. There's no company parameter listed in the intellisense nor an overload.

The intellisense shows no company parameters however when you drill into implementation, Credentials does specify both a company and tenant parameter. There seems to be a logic or code error here. 

Remedy now is to NOT specify any of the additional parameters except username, password.

Using both 20.200.001 and the newer 22.200.001 both exhibit this error.

**Comment by Dmitrii-Naumov** [comment]
Fixed
