### ISSUE TITLE
RequestLogger adds parameters twice in logs

### ISSUE THREAD

**Issue by samol518** [Acumatica/AcumaticaRESTAPIClientForCSharp#20]
The request in the logs have the parameter list twice 
the issue comes from here
writer.WriteLine("\tURL: " + restClient.BuildUri(request) + parameters);
the part "restClient.BuildUri(request)" already contains the parameters so adding parameters to it adds them twice
which can result in something like this
------------------------
https://eivape.acumatica.com/entity/Default/20.200.001/Shipment/SHP011445
?%24select=Details%2fInventoryID%2cDetails%2fWarehouseID%2cDetails%2fShippedQty%2cDetails%2fLineNbr&%24expand=Details
?$select=Details/InventoryID, Details/WarehouseID, Details/ShippedQty, Details/LineNbr&$expand=Details
-------------------------

**Comment by Dmitrii-Naumov** [comment]
Fixed
