### ISSUE TITLE
OData calls hang in WinForms projects

### ISSUE THREAD

**Issue by scottstanaland** [Acumatica/AcumaticaRESTAPIClientForCSharp#52]
I'm running into an odd issue making an OData call from within a WinForms project.

Any OData call I make just hangs and never completes.  I never get a response, not even a timeout.

The same exact code works fine in a console application.  

I have only tried OData in WinForms, I'm not sure if the same issue occurs with a regular API call.

Here's a screenshot of the very simple call.

![image](https://github.com/Acumatica/AcumaticaRESTAPIClientForCSharp/assets/98192449/e41eaecf-c16c-4975-acbd-0cc5e8153257)

**Comment by scottstanaland** [comment]
I appear to hit the same issue with a standard REST API call also.  It hangs as soon as I attempt the login.  I have also updated my packages to the 5.0 version with the same results.

**Comment by dnaumov** [comment]
@scottstanaland it's because of the way Async calls are handled with Win Forms. It's fixed in 5.0
