### ISSUE TITLE
URL request generated using SalesOrderAPI doesn't add the TOP parameter when specified.

### ISSUE THREAD

**Issue by stevenh-ACM** [Acumatica/AcumaticaRESTAPIClientForCSharp#55]
Writing a demo app where I am using the TOP parm to limit return sets. After setting it and seeing no difference, I retrieved the request using the Interceptor and the parm is not in the composed URL. The other items are but not the TOP parm.

Correct URL request:
https://acu-demos.us/acumaticaerp/entity/Default/22.200.001/salesorder?$select=OrderType,OrderNbr,Status,Date,Shipments/ShipmentDate,CustomerID,OrderedQty,OrderTotal,CurrencyID, LastModified&$filter=Date gt datetimeoffset'2024-02-01T00:00:00' and Date le datetimeoffset'2024-05-19T00:00:00' and OrderType eq 'SO'&$expand=Shipments&$custom=&$skip=0&$top=5

Composed by SalesOrderAPI:
https://acu-demos.us/acumaticaerp/entity/Default/22.200.001/salesorder?$select=OrderType,OrderNbr,Status,Date,Shipments/ShipmentDate,CustomerID,OrderedQty,OrderTotal,CurrencyID, LastModified&$filter=Date gt datetimeoffset'2024-02-01T00:00:00' and Date le datetimeoffset'2024-05-19T00:00:00' and OrderType eq 'SO'&$expand=Shipments

Note that $top=5 is not in the request.

**Comment by dnaumov** [comment]
Fixed in version 5.2.0

**Comment by stevenh-ACM** [comment]
Great
